### create
POST localhost:8080/api/v1/article/closed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAwOTYxMDYsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjkwOTYwMTA2LCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.orrnPQqSnNL5-UmF3DxPdWYb_Q5ZdO2nxS2wi1DMvycgLBYjMWa8GaqPCVGv0iQe0HeQwnRO0Pj_kCOLDLnckQ

{
  "title": "test3",
  "description": "test3",
  "content": "msdsddsadasdsadsad",
  "regionId": 1,
  "categoryId": 1,
  "articleTypes": [1],
  "tagList": [1,4],
  "imageId": "2747d28f-8e68-4736-9bee-1c800aade4c4"
}

### update by moderator
PUT localhost:8080/api/v1/article/closed/5499948d-b800-4639-9300-d768f9f75cc1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAxOTQyNTcsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjkxMDU4MjU3LCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.pcxXqxPn_69U3r3tusUuVwEkofz4nm14B1MpH1zL8ZogB7ilzX-YkAStrjRBjwwf4AKrcVFIyCUfpWGiQocZ9Q

{
    "title": "test1  updated",
    "description": "test1 updated",
    "content": "dsadd",
    "regionId": 1,
    "categoryId": 1,
    "articleTypes": [1,2],
    "tags": [2,3],
    "imageId": "d28cdbed-03d2-4137-98c6-b6b85a0c0725",
    "articleTagList": [1,4]
}
### delete article moderator
DELETE localhost:8080/api/v1/article/closed/23c504e0-e29e-4a64-8000-4b9f5a83f9ac
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAxOTQyNTcsImlkIjozLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjkxMDU4MjU3LCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.pcxXqxPn_69U3r3tusUuVwEkofz4nm14B1MpH1zL8ZogB7ilzX-YkAStrjRBjwwf4AKrcVFIyCUfpWGiQocZ9Q
### update status
PUT localhost:8080/api/v1/article/closed/updateStatus/5499948d-b800-4639-9300-d768f9f75cc1?status=PUBLISHED
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAwMTkwNTcsImlkIjoyLCJyb2xlIjoiUFVCTElTSEVSIiwiZXhwIjoxNjkwODgzMDU3LCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.EREFn-5dtjOlEhl2AYwLQXHZKpvGlb-sTT5CNdLXPCKdrzzrH3mn04u1m419dtW3VpMMwO4BDNDm7pb9mZlhRg

### get last five
GET localhost:8080/api/v1/article/getLast?typeId=1&amount=3
Content-Type: application/json

### get last three by type
#GET localhost:8080/api/v1/article/getLastThree?typeId=1
#Content-Type: application/json



### get last eight
GET localhost:8080/api/v1/article/getLastEight
Content-Type: application/json

[
  "6745d902-6b2f-4442-a140-9678a49a097c","10fec872-5e11-4c1e-8fcc-1625e34e0e96","6a93de29-b3b1-4331-bd10-a9765a0845ec",
  "9757de0d-2c85-40cb-8e6d-901077623b9f"
]

###  8. Get Article By Id And Lang
GET localhost:8080/api/v1/article/getByLang?articleId=5499948d-b800-4639-9300-d768f9f75cc1&lang=En

### 9. Get Last 4 Article By Types and except given article id.
GET localhost:8080/api/v1/article/getLastFour/5499948d-b800-4639-9300-d768f9f75cc1?typeId=1

###10. Get 4 most read articles
GET localhost:8080/api/v1/article/getMostViewed

### 11 get by tag
GET localhost:8080/api/v1/article/getByTag?tag=#UzAM
### 12. Get Last 5 Article By Types  And By Region Key
GET localhost:8080/api/v1/article/getByTypeAndRegion?typeId=1&regionId=1
### 13. Get Article list by Region Key (Pagination)
GET localhost:8080/api/v1/article/paginationByRegion?regionId=1&page=1&size=10

