### like
POST localhost:8080/api/v1/articleLike/like/17aa3781-221c-4c85-aa1f-ecfc88732fd8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE1ODUxMDAsInBob25lIjoiKzk5ODkwMDEwMjAzMCIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2OTE2NzE1MDAsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.b7NqKdNriJcU0Gma9SQwVeoAYNvgryJmIfFp5Zfyc-zZADTwfySetln7iRaPRJEUEckx6l49wWm2ubNM7wUtJQ

### dislike
POST localhost:8080/api/v1/articleLike/dislike/17aa3781-221c-4c85-aa1f-ecfc88732fd8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE1ODQ3MzgsInBob25lIjoiKzk5ODkwMDEwMTAyMiIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2OTE2NzExMzgsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.NYUy-z3yoRkMQvzO9m4OMtm1pQn7uMrsgyzENQGJouwouSXrJhpdLUUlQYfZDU8n9TA32_yrh5UCvuz8l1974A

### remove
DELETE localhost:8080/api/v1/articleLike/remove/1194c3bd-eb0b-487a-b066-680b4fe019f4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE1ODQ3MzgsInBob25lIjoiKzk5ODkwMDEwMTAyMiIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2OTE2NzExMzgsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.NYUy-z3yoRkMQvzO9m4OMtm1pQn7uMrsgyzENQGJouwouSXrJhpdLUUlQYfZDU8n9TA32_yrh5UCvuz8l1974A
