### create by admin
POST localhost:8080/api/v1/articleType/admin
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk5MzM0MzcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTAwMTk4MzcsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.1t4XM3srv4-STI1UzoHvjWM3e8xnEWgxdt5e2wLN4Tyq5YbglCQ7vs2dWFTVHna_QIxcB5qrvSX5wBo65I6hrQ

{
  "orderNumber": 3,
  "nameEn": "Video news",
  "nameUz": "Video yangiliklar",
  "nameRu": "Video novostiy"
}
//{
//  "orderNumber": 1,
//  "nameEn": "Main",
//  "nameUz": "Asosiy",
//  "nameRu": "Главный"
//}

### update by admin
PUT localhost:8080/api/v1/articleType/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw


{
  "orderNumber": 2,
  "nameEn": "Breaking News",
  "nameUz": "Dolzarb",
  "nameRu": "Последние новости"
}
### delete by admin
DELETE localhost:8080/api/v1/articleType/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### get all admin
GET localhost:8080/api/v1/articleType/getAll?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### get by lang
GET localhost:8080/api/v1/articleType/language?lang=En
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw
