### create by admin
POST localhost:8080/api/v1/articleType/admin
Content-Type:  application/json
Authorization: Basic Kzk5ODkwODA3MDE3NjoxMjM0NQ==

{
  "orderNumber": 4,
  "nameEn": "Breaking news",
  "nameUz": "dolzarb xabarlar",
  "nameRu": "srochniy novosti"
}


### update by admin
PUT localhost:8080/api/v1/articleType/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw


{
  "orderNumber": 2,
  "nameEn": "Breaking News",
  "nameUz": "Dolzarb",
  "nameRu": "Последние новости"
}
### delete by admin
DELETE localhost:8080/api/v1/articleType/1
Authorization: Basic Kzk5ODkwODA3MDE3NjoxMjM0NQ==

### get all admin
GET localhost:8080/api/v1/articleType/getAll?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### get by lang
GET localhost:8080/api/v1/articleType/language?lang=En
Authorization: Basic Kzk5ODkwODA3MDE3NjoxMjM0NQ==
