 ### create
POST localhost:8080/api/v1/article/closed
Content-Type: application/json
Authorization: Basic Kzk5ODk5MzAzMDMwMzoxMjM0NQ==

{
  "title": "test6",
  "description": "test8",
  "content": "msdsddsadasdsadsad",
  "regionId": 1,
  "categoryId": 1,
  "articleTypes": [1],
  "tagList": [1,4],
  "imageId": "2747d28f-8e68-4736-9bee-1c800aade4c4"
}

### update by moderator
PUT localhost:8080/api/v1/article/closed/5499948d-b800-4639-9300-d768f9f75cc1
Content-Type: application/json
Authorization: Basic Kzk5ODk5MzAzMDMwMzoxMjM0NQ==

{
    "title": "test6  updated",
    "description": "test17 updated",
    "content": "dsadd",
    "regionId": 1,
    "categoryId": 1,
    "articleTypes": [1,2],
    "tags": [2,3],
    "imageId": "d28cdbed-03d2-4137-98c6-b6b85a0c0725",
    "articleTagList": [1,4]
}

### delete article moderator
DELETE localhost:8080/api/v1/article/closed/6e75b2e5-f4c0-4750-b5c2-3e76b0e27cc8
Authorization: Basic Kzk5ODk5MzAzMDMwMzoxMjM0NQ==
### update status
PUT localhost:8080/api/v1/article/closed/updateStatus/f0f0c982-18e4-4a59-b248-2037217384a7?status=PUBLISHED
Authorization: Basic Kzk5ODk5OTA5MDkwOToxMjM0NQ==

### get last five
GET localhost:8080/api/v1/article/public/getLast?typeId=1&amount=5


### get last three by type
#GET localhost:8080/api/v1/article/getLastThree?typeId=1
#Content-Type: application/json



### get last eight
GET localhost:8080/api/v1/article/public/getLastEight
Content-Type: application/json

[
  "6745d902-6b2f-4442-a140-9678a49a097c","10fec872-5e11-4c1e-8fcc-1625e34e0e96","6a93de29-b3b1-4331-bd10-a9765a0845ec",
  "9757de0d-2c85-40cb-8e6d-901077623b9f"
]

###  8. Get Article By Id And Lang
GET localhost:8080/api/v1/article/public/getByLang?articleId=5499948d-b800-4639-9300-d768f9f75cc1&lang=En
### 9. Get Last 4 Article By Types and except given article id.
GET localhost:8080/api/v1/article/public/getLastFour/5499948d-b800-4639-9300-d768f9f75cc1?typeId=1
###10. Get 4 most read articles
GET localhost:8080/api/v1/article/getMostViewed
### 11 get by tag
GET localhost:8080/api/v1/article/getByTag?tag=#UzAM
### 12. Get Last 5 Article By Types  And By Region Key
GET localhost:8080/api/v1/article/open/getByTypeAndRegion?typeId=1&regionId=1
### 13. Get Article list by Region Key (Pagination)
GET localhost:8080/api/v1/article/paginationByRegion?regionId=1&page=1&size=10
### 14. Get Last 5 Article Category Key
GET localhost:8080/api/v1/article/getLastFiveByCategory/1
### 15. Get Article By Category Key (Pagination)
GET localhost:8080/api/v1/article/getByCategoryPagination/1?page=1&size=10
### 16. Increase Article View Count by Article Id
PUT localhost:8080/api/v1/article/increaseViewCount/5499948d-b800-4639-9300-d768f9f75cc1
###17. Increase Share View Count by Article Id
PUT localhost:8080/api/v1/article/increaseShareCount/5499948d-b800-4639-9300-d768f9f75cc1
### 18 filter pagination
POST localhost:8080/api/v1/article/closed/filterPagination?page=1&size=10
Content-Type: application/json
Authorization: Basic Kzk5ODk5OTA5MDkwOToxMjM0NQ==

{
  "publishedDateTo": "2023-07-30"
}

