### login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "phone": "+998993030303",
    "password": "12345"
}

### register user
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Vandam",
  "surname": "VAliyev",
  "email": "bandam@gmail.com",
  "phone": "+998900102030",
  "password": "vandam123",
  "photoId"
}