### login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "phone": "+998900102035",
    "password": "12345"
}

### registr user by email
POST localhost:8080/api/v1/auth/registrationByEmail
Content-Type: application/json

{
  "name": "test5",
  "surname": "test5",
  "email": "runnerpro1790@gmail.com",
  "phone": "+998900101077",
  "password": "12345",
  "photoId" :"d474a0f4-2246-4e7b-b83d-53fb9d8d3112"
}

### registr user by phone
POST localhost:8080/api/v1/auth/registrationByPhone
Content-Type: application/json

{
  "name": "test6",
  "surname": "test6",
  "email": "test1960@gmail.com",
  "phone": "+998900161022",
  "password": "12345",
  "photoId" :"d474a0f4-2246-4e7b-b83d-53fb9d8d3112"
}

### verification by phone
GET localhost:8080/api/v1/auth/verification/phone?phone=998900101022&message=25564
