### create by admin
POST localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Basic Kzk5ODkwODA3MDE3NjoxMjM0NQ==

{
  "orderNumber": 1,
  "nameEn": "Local",
  "nameUz": "Maxaliy",
  "nameRu": "Local"
}

### update by admin
PUT localhost:8080/api/v1/category/admin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA4OTI5MjUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTE3NTY5MjUsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.NnTzYADYENhhgziKSis2JzWlszncV1rzX99UdfnFV87T1oF7kCoLPkj-ljSjOoMt4pUxNvTblXolC7zLUrHDQg

{
  "orderNumber": 2,
  "nameEn": "Sport",
  "nameUz": "Sport",
  "nameRu": "Спорт"
}
### delete by admin
DELETE localhost:8080/api/v1/category/delete/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### get all by admin
GET localhost:8080/api/v1/category/getAll
Authorization: Basic Kzk5ODkwODA3MDE3NjoxMjM0NQ==

### get by language
GET localhost:8080/api/v1/category/public/language?lang=Uz
