### create admin(admin)
POST localhost:8080/api/v1/profile
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "ali@gmail.com",
  "phone": "+998908070176",
  "password": "ali123",
  "role": "ADMIN"
}

### create staff(admin)
POST localhost:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk5Mjc1MTMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk5MzExMTMsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.7dknxQsvJG-dCLmC0sTRf_KIIoCC-z6Sq1gdsAjL4VodLOPiKCUUh_fMM7Ww2iqKujQyaMYKm2b3sSfqRa03RA

{
  "name": "Eshmat",
  "surname": "Eshmatov",
  "email": "esh@gmail.com",
  "phone": "+998993030303",
  "password": "12345",
  "role": "MODERATOR"
}

### staff Update By Admin
PUT localhost:8080/api/v1/profile/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAwMTg3NjksImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA4ODI3NjksImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.gX0tCNbABOtMZZe9m9JHKMwQPRNs-LUAAd4c_j6cxHbRR974ll1AtHU6uGJnkWRV1mUJA_MlIR34zN8ZY-gGrA

{
  "password": "12345"
}
### updateStaffByStaff
PUT localhost:8080/profile/updateStaffByStaff/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

{
  "name": "Ali",
  "surname": "Aliyev"
}

### update photo any
PUT localhost:8080/api/v1/profile/updatePhoto?photoId=2747d28f-8e68-4736-9bee-1c800aade4c4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAxOTE1NDgsImlkIjoyLCJyb2xlIjoiUFVCTElTSEVSIiwiZXhwIjoxNjkxMDU1NTQ4LCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.un9b29Wrd9GJ7dJzIR9-VY1WnomVwOZQ1PVT0-sxaDOykNXHngjnwKDA_5SWKe7_dr1V9JNg92oloUkBpCdXzA
### profileListPaginationByAdmin
GET localhost:8080/api/v1/profile/profileListPagination?page=1&size10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### delete profile by id
DELETE localhost:8080/api/v1/profile/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### filter pagination by Admin
POST localhost:8080/api/v1/profile/filterPagination?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3ODUwOTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3ODg2OTEsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.-52wXvcwP7CNmLIfEB0P1ClHpSnC1f-vniFLbQ5bPPC7VhZ9I5EKfYJ3JeOdi1PaHmbduTjqaTLAw7884pQIrA

{
  "created_date_from": "2023-07-01",
  "created_date_to": "2023-07-14"
}
