### create admin(admin)
POST localhost:8080/api/v1/profile
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "ali@gmail.com",
  "phone": "+998908070176",
  "password": "ali123",
  "role": "ADMIN",
  "prtId": 1
}

### create staff(admin)
POST localhost:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NzY1NzcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3ODAxNzcsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9._KOIHK3fTuHCeXieyf0WUs4qT5jGJRkt0fwMSO5W3C7lIbHT4QC4rYDz49nzp0WTgrO0uvdzk0jqFoIp7iLabA

{
  "name": "Toshmat",
  "surname": "VAliyev",
  "email": "wwali@gmail.com",
  "phone": "+998328070176",
  "password": "vali123",
  "role": "PUBLISHER",
  "prtId": 1
}

### staff Update By Admin
PUT localhost:8080/profile/staffUpdateByAdmin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

{
  "name": "Vali",
  "surname": "VAliyev",
  "email": "vali@gmail.com",
  "phone": "+998909090909",
  "password": "ali123",
  "role": "PUBLISHER"
}
### updateStaffByStaff
PUT localhost:8080/profile/updateStaffByStaff/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "ali@gmail.com",
  "phone": "+998909099999",
  "password": "ali123"
}
### profileListPaginationByAdmin
GET localhost:8080/api/v1/profile/profileListPagination?page=1&size10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### delete profile by id
DELETE localhost:8080/api/v1/profile/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjYxMTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3Njk3MTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.pHV1kTy7tUzOZ-TmTT5CmE_Ma92PENYd85YJFQDUef3Myxp_9Hi_2yJrmxZgCgZwwkiScXMFNgKiW56v2QQxKw

### filter pagination by Admin
POST localhost:8080/api/v1/profile/filterPagination?page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3ODUwOTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3ODg2OTEsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.-52wXvcwP7CNmLIfEB0P1ClHpSnC1f-vniFLbQ5bPPC7VhZ9I5EKfYJ3JeOdi1PaHmbduTjqaTLAw7884pQIrA

{
  "created_date_from": "2023-07-01",
  "created_date_to": "2023-07-14"
}
